language: minimal

branches:
  only: 
    - master
    
jobs:
  include:
   - os: linux
     arch: amd64
   - os: linux
     arch: arm64
env:
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
      arch="-arm64"
    else
      arch=""
    fi
services:
  - docker

script:
  - docker build
    -t "subham328/alpine-ci-tools:latest'{arch}'"
    -t "subham328/alpine-ci-tools:$TRAVIS_BUILD_NUMBER'{arch}'"
    --build-arg VCS_REF=`git rev-parse --short HEAD` .;
  - docker run "subham328/alpine-ci-tools:$TRAVIS_BUILD_NUMBER"{arch}"" kubectl version --client;
  - docker run "subham328/alpine-ci-tools:$TRAVIS_BUILD_NUMBER"{arch}"" helm version --client;
  - docker run "subham328/alpine-ci-tools:$TRAVIS_BUILD_NUMBER"{arch}"" helm3 version --client;
  - docker run "subham328/alpine-ci-tools:$TRAVIS_BUILD_NUMBER"{arch}"" az --version;

before_deploy:
  - docker login -u subham328 -p Ak@sh328
  
deploy:
  provider: script
  script: 
    - if [ "${TRAVIS_CPU_ARCH}" != "arm64" ]; then
        docker push "subham328/alpine-ci-tools:latest" && docker push "subham328/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" ;
      else
        docker push "subham328/alpine-ci-tools:latest-arm64" && docker push "subham328/alpine-ci-tools:$TRAVIS_BUILD_NUMBER-arm64" ;
      fi
  on:
    branch: master
