language: minimal

branches:
  only: 
    - master
    
arch:
  - amd64
  - arm64
   
services:
  - docker

script:
  - docker build
    -t "lareeth/alpine-ci-tools:latest"
    -t "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER"
    --build-arg VCS_REF=`git rev-parse --short HEAD` .
  - docker run "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" kubectl version --client
  - docker run "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" helm version --client
  - docker run "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" helm3 version --client
  - docker run "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" az --version 

before_deploy:
  - docker login -u subhamkumarpuresoftware -p Ak@sh328
  
deploy:
  provider: script
  script: docker push "lareeth/alpine-ci-tools:latest" && docker push "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER"
  on:
    branch: master
© 2021 GitHub, Inc.
